### ISSUE TITLE
An alternative for `.ar` TLD

### ISSUE THREAD

**Issue by charmful0x** [decentldotland/ANS#2]
## Introduction
The current ANS spec introduced the `"label" + dot + "ar"` format to label Arweave addresses. The reason to follow this format is to be compatible with other already-existing Domain Names Services protocols (e.g. ENS, PolkaDomains, UnstoppableDomains, etc).

## Compatibility Possible Conflict
`.ar` already exists as a ccTLD for Argentina, the thing that can create conflicts in the future once ANS domains gain a big vast adoption and integrations. As well as labels resolving in web2 browsers for Arweave hosted content hash.

Not using `.ar` also give ANS a weird UX for its users because ANS is a public & open protocol for Arweave apps, not domain-limited (decent.land)

## Issue's Proposal

TLD name proposal in this issue is `.psd` ; The "PSD" string is not registered yet in CANN TLDs ( see https://data.iana.org/TLD/tlds-alpha-by-domain.txt)

### nomenclature

"PSD" refers to "Profit Sharing Domain". The nomenclature does also give a hint on how the ANS labels generate profit to its users through the PoR mechanism.

Also, this naming follows the standards used in the Arweave ecosystem either for PSTs (Profit Sharing Tokens) or PSCs (Profit Sharing Communities, equivalent to DAOs). Hence, `.psd` fits well in identifying the new asset type in the Arweave network that is introduced by ANS (labels are digital properties, assets).

###  UPDATE:
the `.psd` string may provoque another conflict with "Photoshop Document", thus the new suggested TLDs are: `.ans`  and `.arw`

## Author(s)

- Charmful0x aka Darwin

**Comment by martonlederer** [comment]
I really like `.ans`, `.arw` is nice tho. I'd also suggest `.arn` for Arweave Name

**Comment by charmful0x** [comment]
`.arn` is available as TLD and also meaningful. Good suggestion! 🤝

**Comment by charmful0x** [comment]
As the `.ar` TLD has been used for ANS domains for the Testnet protocol release, this issue will be closed considering `.ar` has reached the consensus.

- [ANS Testnet Release v0.0.1](https://github.com/decentldotland/ANS/releases/tag/v0.0.1)
- [ANS Genesis Airdrop](https://github.com/decentldotland/ANS-Testnet-Airdrop)
- ANS Domain Resolver ([ar.page](https://ar.page)) -- e.g. [darwin.ar.page](https://darwin.ar.page)

Thanks, everyone!
